### ISSUE TITLE
More samples on GitHub page

### ISSUE THREAD

**Issue by pzdcdoc** [pzdcdoc/pzdcdoc#12]
- Links to Maven artifacts 
- Short example of using
- Key benefits comparing to bare asciidoctor-j: ready to use, single command
- Multiple repositories generation demo, e.g. PzdcDoc itself, AsciiDoctor, AciiDoctor-J
-

**Comment by Pingvin235** [comment]
Format samples in project.

**Comment by Pingvin235** [comment]
Terms lists.
::Blabla

Select asciidoctor manual as a subproject, also demo and README.
