### ISSUE TITLE
Missing demos (swapped with #24)

### ISSUE THREAD

**Issue by Pingvin235** [pzdcdoc/pzdcdoc#23]
Cross links to config

Terms list

**Comment by Pingvin235** [comment]
Includes

**Comment by Pingvin235** [comment]
Linked project file.

**Comment by pzdcdoc** [comment]
Schema.
[schema.txt](https://github.com/pzdcdoc/pzdcdoc/files/3717398/schema.txt)

**Comment by Pingvin235** [comment]
https://github.com/stathissideris/ditaa

**Comment by pzdcdoc** [comment]
DB structure.

**Comment by Pingvin235** [comment]
https://powerman.name/doc/asciidoc
https://mrhaki.blogspot.com/2014/06/awesome-asciidoc-use-link-attributes.html

**Comment by Pingvin235** [comment]
Workflow link.

**Comment by Pingvin235** [comment]
Documentation - is program for humans.
Link to snippets in BGERP?

**Comment by Pingvin235** [comment]
https://blog.regehr.org/archives/1653

**Comment by Pingvin235** [comment]
https://jaxenter.de/asciidoc-gradle-eclipse-75169

**Comment by Pingvin235** [comment]
https://asciidoctor.org/docs/user-manual/#description-list
